---
title: "2weeks"
author: "zang"
date: "2015년 9월 21일"
output: html_document
---
   
   
   
   
#함수찾기
   
   
   
```{r}
a<-c(0,1,1,0,0,1,1,1,0,1,1)
b<-c(a,c(2,2,4,1,1,1,1,0,2))
c<-rep(c(1,0),c(8,7))
a
b
c
```

```{r, echo=FALSE}
my<-function(x,n){
  x<-which(x%%2==1)
  n<-n-1
  return(x[c(diff(x,n)==n,rep(F,n))])
}
```

```{r}
my(a,2)
my(a,3)
my(a,4)
my(b,2)
my(b,3)
my(b,4)
my(c,2)
my(c,3)
my(c,4)
```

---
   
   
   
   
   
#몬테카를로 시뮬레이션
   
   
   
      
>몬테카를로 시뮬레이션으로 적분을 해보자
   
   
   
   
##그래프와 면적계산
```{r}
#x,y 좌표 random하게 생성
x<-runif(100,0,1)
y<-runif(100,exp(-1),exp(0)) 
z<-exp(x-1) # x,z 기준 그래프 생성
plot(x,y,xlim=c(0,1),ylim=c(0,1)) #그래프 그려보기
abline(line(x,z),col="red") 
prob<-mean(y<=z)#실제 (x,y) 비교값 (x,z) 밑에 있는확률구하기
(solution<-(exp(0)-exp(-1))*prob)#면적계산,전체면적*확률
```

## 100 반복 추출 , 모수 추정
```{r}
solution<-rep(0,100)
for ( i in 1:100){
  x<-runif(100,0,1)
  y<-runif(100,exp(-1),exp(0))
  z<-exp(x-1)
  prob<-mean(y<=z)
  solution[i]<-(exp(0)-exp(-1))*prob
}
mean(solution)

```


##10000개의 점을 생성
```{r}
x<-runif(10000,0,1)
y<-runif(10000,exp(-1),exp(0)) 
z<-exp(x-1) 
(prob<-mean(y<=z))
(solution<-(exp(0)-exp(-1))*prob)
```


##1000개 점찍기 100번 반복, 모수 추정
```{r}
solution<-rep(0,100)
for ( i in 1:100){
  x<-runif(1000,0,1)
  y<-runif(1000,exp(-1),exp(0))
  z<-exp(x-1)
  prob<-mean(y<=z)
  solution[i]<-(exp(0)-exp(-1))*prob
}
mean(solution)
```


