---
title: "3weeks homework"
author: "zang"
date: "2015년 9월 22일"
output: html_document
---

#tree과제
   
   
   
##읽어오기
```{r}
setwd("C:\\Users\\ss\\Desktop\\tobig\\3주차-의사결정,장바구니\\의사결정나무")
mushrooms<-read.csv("mushrooms.csv",stringsAsFactors = T)
str(mushrooms)
library(tree)   
```
   
   
##트리만들기
```{r}
mushrooms.tr<-tree(type~.,split = c("gini"),data=mushrooms)
summary(mushrooms.tr)
plot(mushrooms.tr);  text(mushrooms.tr) 

```
   
   
   
##가지치기
```{r}
mushrooms.cv<-cv.tree(mushrooms.tr)
mushrooms.cv 
plot(mushrooms.cv) 
mushrooms.tr4<-prune.tree(mushrooms.tr,best =4)
plot(mushrooms.tr4);text(mushrooms.tr4)
summary(mushrooms.tr4)
```

   
   
   
##traing,test나누기
```{r}
id<-sample(1:8124,round(8124*0.8))
traing_mushrooms<-mushrooms[id,]
test_mushrooms<-mushrooms[-id,]
```

   
   
   
##학습시키기
```{r}
traing_mushrooms_tree<-tree(type~.,split = c("gini"),data=traing_mushrooms)
traing_mushrooms_tree_cv<-cv.tree(traing_mushrooms_tree)
traing_mushrooms_tree_cv
plot(traing_mushrooms_tree_cv)
traing_mushrooms_tree_best<-prune.tree(traing_mushrooms_tree,best=4)
plot(traing_mushrooms_tree_best);text(traing_mushrooms_tree_best)
summary(traing_mushrooms_tree_best)
```
   
   
   
##예측하기
```{r}
predict_mushrooms<-predict(traing_mushrooms_tree_best,test_mushrooms,type="class")
test_mushromms_labels<-test_mushrooms[,1]

```
   
   
   
##결과보기
```{r}
library("caret")
confusionMatrix(data=predict_mushrooms,reference=test_mushromms_labels )
```

---


#2.장바구니 분석



```{r}
library(arules)

groceries<-read.transactions("groceries.csv",sep=",")

groceryrules<-apriori(groceries,parameter = list(support=0.006,confidence=0.25,minlen=2))
summary(groceryrules)
inspect(sort(groceryrules,by="lift")[1:5])

```


